### ISSUE TITLE
transitions not working when a custom component include any transition.

### ISSUE THREAD

**Issue by DoranYun** [sveltejs/svelte-transitions#4]
the example:

https://svelte.technology/repl?version=1.31.0&gist=e9dedb05fee495356046c11316a3bceb

**Comment by Rich-Harris** [comment]
Transitions only work on DOM nodes. You would need to wrap the component, [like so](https://svelte.technology/repl?version=1.31.0&gist=224ea9f247271b71fa85a8a51b19c356). I've opened an issue on Svelte itself so that we can print a helpful error if a transition is applied to a component.

**Comment by Rich-Harris** [comment]
As of Svelte 1.34 this results in a compile error:

![screen shot 2017-08-29 at 11 28 39 am](https://user-images.githubusercontent.com/1162160/29829389-4f5384ce-8cad-11e7-9af3-ba4e56469fee.png)

**Comment by DoranYun** [comment]
👍🏼
